### ISSUE TITLE
[Storage Engine] Rework Kepler's UX mockups according to Kepler's feedback 

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#10]
**Goal:**
To modify the Kepler's UX proposal for **Storage Engine** with following [Kepler's feedback](https://github.com/CartoDB/product/issues/465#issuecomment-533467918).

**Comment by MireyaD** [comment]
Hey!

This is the Invision with the modifications according to the feedback: https://invis.io/TPTSVDX2KF5#/384524982_Home

These are the changes:
- Backend Storage (first option) with more details.
- Backend Storage (Kepler option) with a button at the end of the other panels. The user can close it, and it will be there again the next time they enter in Kepler.
(I think the original proposal works better because it doesn't compete with the rest of the main elements.)
- Create account screens.
- Sign in update with data info.
(About the communication of "what is going to happen with the user data if they connect to CARTO", Agi told us we can communicate it through a checkbox on the login and signup screens)

I would need some help with the copies on the new screens, @vdiego could you help me?

**Comment by VictorVelarde** [comment]
Hi @MireyaD nice work!

For the current implementation in the cycle, we are specially interested in the 'Backend Storage' part and its proper definition. 

I've had a look at the Invision and I would like to add some comments:

- 1. first, we still need to add a 'Title' (mandatory) + 'Description' (probably optional) field when saving Maps. That could be presented in a Modal (first time saving / subsequent savings could omit it).
- 2. I have been checking both options with @rjimenezda, and technically they seem pretty similar. First one makes probably more sense IMO. The second one is feasible, but it lacks of space for certain options.
- 3. Loading map from CARTO. We aren't sure about been able to add the 'map snapshots' on time (Kepler have them pre-generated), so could start with some 'predefined' images (equal for all maps).

I think it's important to consider these details internally, so we can share the proposal upstream and get some relevant feedback soon.

/cc @ana-md

**Comment by ana-md** [comment]
Additional feedback coming from Shan can be found in comments in the [presentation](https://docs.google.com/presentation/d/1H1M1pkDdAupdrveOEhs3DjGH0H7PLWyLYv5ZMJU1MRs/edit#slide=id.g6029048053_4_348). 
@MireyaD please take a look at it when discussing this with @VictorVelarde and @rjimenezda :)

**Comment by MireyaD** [comment]
Hey!! Thanks for your comments!

I worked on the improvements for the storage engine, and these are the changes:

- Including a modal with the fields "Title" and "Description" when saving Maps. The title field should be limited to 40 characters, and the text area should be limited to 70 characters.
- Another option for "Maps created on Kepler" in the "Load via Storage" just in case we can't add the map snapshots on time.
- Adding a step in "Load via Storage" (was CARTO previously) to make it easier to connect to other data backend in the future. The flow right now is: Add data to map > Load via Storage > CARTO Storage.
- Changing the copy for the save button, "Save" instead of "Save data".
- Creating a button status when the user is logged in but nothing has been loaded yet.

### Storage Engine v1 

https://invis.io/TPTSVDX2KF5#/386402482_Storage_V1_-_Home 

The connection to the Backend Storage is integrated into the sidebar. 

I think this is the best option because: 
It's less intrusive for the user.
We can give them more information about the CARTO Backend Storage before they click
If they have more integrations in the future, it's easier to include them here since they have more space.

### Storage Engine v2

https://invis.io/TPTSVDX2KF5#/386401108_Storage_V2

The connection to the Backend Storage is outside the sidebar. Wherever the user navigates, it will be visible unless they close it. It will reappear the next time the user enters in Kepler.

**Comment by VictorVelarde** [comment]
After having reviewed these latest invision together we're moving it the conversation to https://github.com/CartoDB/kepler.gl/issues/13
