### ISSUE TITLE
Create issue @kepler.gl for 'Storage engine'

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#13]
We can write the proposal here and, after reviewing it share it upstream

**Comment by VictorVelarde** [comment]
This is their **Feature request template**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by VictorVelarde** [comment]
## Storage engine

### 1. Basics

**Is your feature request related to a problem? Please describe.**
Kepler.gl has a 'Save/Share your map' feature using Dropbox but it doesn't have a way to manage privately the maps (& datasets) after its creation. 

**Describe the solution you'd like**
An integrated and private system to persist / load easily from an external provider Maps & Datasets

**Describe alternatives you've considered**
- Set a generic approach, useful for any cloud provider. 
- Implementation in CARTO, as it has several APIs to manage persistence and it could also be a valuable tool for Kepler users.

### 2. Additional context

These are our mock-up proposals after integrating your feedback after the [first presentation](https://docs.google.com/presentation/d/1H1M1pkDdAupdrveOEhs3DjGH0H7PLWyLYv5ZMJU1MRs/edit#slide=id.g6029048053_0_243).

- *Storage Engine v1* https://invis.io/TPTSVDX2KF5#/386402482_Storage_V1_-_Home
   - The connection to the Backend Storage is integrated into the sidebar.
   - We think this is the best option because it's less intrusive for the user. We can give them more information about the CARTO Backend Storage before they click. If they have more integrations in the future, it's easier to include them here since they have more space.

- *Storage Engine v2* https://invis.io/TPTSVDX2KF5#/386401108_Storage_V2
   - The connection to the Backend Storage is outside the sidebar. Wherever the user navigates, it will be visible unless they close it. It will reappear the next time the user enters in Kepler.

### 3. Technical Notes

#### 3.1. Generic approach

We propose a generic approach, in which any cloud provider with an OAuth API can include a predefined set of methods to implement the storage engine feature. And that will allow the user to persist maps and datasets, with privacy control, and to get them back from the provider with a set of visual components in Kepler (a new section in the "Add Data to Map" modal).

The first method would be one for declaring provider's *capabilities*. We're proposing these:

- a) map public sharing (public url, like dropbox provider currently does)
- b) map private sharing (restricted url)
- c) dataset management (an optional feature to store & manage datasets separately from the maps themselves, but linked to them).

- **MAPS**. We propose these main methods:
  - *createVisualization*. it persists the whole map's configuration and datasets in the cloud provider, and it returns a unique id for it. The metadata associated to the visualization includes:
    - name
    - description
    - thumbnail
    - privacy
  - *updateVisualization*. it allows updating a visualization, keeping its id but updating some other properties (eg. new description, change privacy, new style and datasets...).
  - *getVisualizations*: all / public / private. Grabs basic info from them, without returning their contents (configuration & datasets).
  - *getVisualization(id)*: it gets a specific vis.
  - *deleteVisualization(id)*: it removes the map from the storage.

- **DATASETS**. For those providers willing to add finer grained control. Some basic methods like:
  - *getDatasets*. get a proper list of datasets that can be loaded in a kepler map (compatible format such as geojson or csv).
  - [ MORE ? ] *TO BE DISCUSSED*

#### 3. 2. Internal notes about CARTO storage provider

The basic mechanism would be a set of simple HTTP remote calls underneath to use the persistence capabilities of the CARTO platform APIs (namely the SQL API). Those API requests to read & write maps and datasets would be encapsulated in a CARTO JavaScript library, so the code should be quite concise in the kepler.gl side. Internally, a set of specific tables would be created in the CARTO user database, to manage private maps and datasets.

In our particular case, the data for the map will be stored separately, since it maps nicely to the concept of a *dataset in CARTO*. This is an implementation detail, and other providers could choose to store everything together, eg. on a single JSON file (config + data) and not provide any *dataset management* capability.

CARTO also allows serving the datasets stored on the platform as many different formats: CSV, geojson, SVG, etc, so this will also be part of the CARTO Storage engine integration as well, a list of user datasets that you can import to the platform.

After a proper integration, the user would be able to manage (list, share, delete) the maps previously created from the CARTO Dashboard.

**Comment by VictorVelarde** [comment]
Ey @rjimenezda please have a look at this 🔝 and feel free to add / modify.

**Comment by VictorVelarde** [comment]
Please @rjimenezda have a look at this 🔝

**Comment by ana-md** [comment]
@MireyaD will take a look at the comments and feedback in [here ](https://github.com/CartoDB/kepler.gl/issues/10) for the mockups and discuss it with @VictorVelarde and @rjimenezda.
Once that is clear, we can add them here together with the technical notes and we can create the issue in Kepler's repository.

**Comment by VictorVelarde** [comment]
We have integrated the latest mockups.

We now need the tech. notes and it will be ready to create upstream

**Comment by VictorVelarde** [comment]
I have added some tech notes 🔝 . Please @rjimenezda have a quick look at it, before we create the final issue with the whole proposal

**Comment by rjimenezda** [comment]
I've expanded and reworded some things, feel free to tweak it

## Revised Technical Notes

This proposal would work extending and complementing the current public sharing option. The basic mechanism would be also a set of simple HTTP remote calls underneath to use the persistance capabilities of the CARTO platform APIs (namely the SQL API). Those API requests to read & write maps and datasets would be encapsulated in a CARTO Javascript library, so the code should be quite concise in the kepler.gl side.

Internally, a set of specific tables would be created in the CARTO user database, to manage private maps and datasets, in the same manner that they have been created for public sharing. In the future, this could evolve to a fully fledged API.

Regarding to what would be persisted:

- The whole map's configuration as .json in a field 
- A title
- An optional description
- A screenshot of the map, if we we are able to.

This data can be then retrieved on a new section of the "Add Data to Map" modal, where it will be presented as a list of components.

In our particular case, the data for the map will be stored separately, since it maps nicely to the concept of a dataset in CARTO. This is an implementation detail, and other providers could choose to store everything on a single JSON file (config + data).

We will also store an exact copy of the dataset, in order to "cartodbfy" it. This is a required process to use the datasets on our own tools.

CARTO also allows serving the datasets stored on the platform as many different formats: CSV, geojson, SVG, etc, so this will be part of the CARTO Storage engine integration as well, a list of user datasets that you can import to the platform.

After a proper integration, the user would be able to manage (list, share, delete) the maps previously created from the CARTO Dashboard.

The current cloud providers approach could be extended to support all of this functionality. We propose adding the following to each provider:

- A method to check for capabilities of the engine (public sharing, private sharing, dataset listing).
- Methods to do CRUD operations on privately-saved maps.
- A method to list datasets.

**Comment by VictorVelarde** [comment]
Cool, thx a lot @rjimenezda for writing more details. I'm gonna update our current text 🔝 https://github.com/CartoDB/kepler.gl/issues/13#issuecomment-533514417

**Comment by VictorVelarde** [comment]
I think everything is ready from our side for opening the Issue upstream. A quick check @ana-md ?

**Comment by ana-md** [comment]
@VictorVelarde  looks good to me too. Just rephrased something in the mockups section and added the link to the first presentation for context. Thanks everyone! :)

**Comment by VictorVelarde** [comment]
@alasarr maybe you want to have a look at it before sending it to Uber?
https://github.com/CartoDB/kepler.gl/issues/13#issuecomment-533514417

**Comment by alasarr** [comment]
It looks pretty well but a couple of comments:

**Regarding design**

I don't see any screenshot to: delete a dataset or to delete/edit a map.  For editing a map I mean to change the title and description.

Appart of sending the link I'll add the two main screenshot because it makes easier to understand

![image](https://user-images.githubusercontent.com/1161870/66371286-13a48180-e9a3-11e9-83ed-c3444c13c422.png)

![image](https://user-images.githubusercontent.com/1161870/66371314-20c17080-e9a3-11e9-8bd1-59caf816e825.png)
☝️ with both tabs opened, but only with a reduced number of maps to make room for seeing the content of both.


**Regarding technical notes**

I'd like to emphasize more the generic approach, i.e., other cloud providers could implement a storage engine, it shouldn't be just CARTO. 

Any provider with an OAuth API and a way to store files could implement this. We propose adding the following abstract method each provider should complete:

Datasets:
We always keep the same structure of the dataset of the user.
- List available datasets
- Upload a dataset. Overwrite datasets.
- Delete a dataset
- Change dataset privacy (private or public)
- Load into an existing 

Maps:
Metadata object to track ... (used layers, name, title, ...)
- Save a new map
- Edit a map: change name, title, layers
- Change map privacy. 
- Delete a map


☝️ @VictorVelarde @rjimenezda check this and complete it with more details.

I think we talked too much about the implementation at our side. For example, I won't include at a first conversation the `cartobdfy`.

**Comment by MireyaD** [comment]
> I don't see any screenshot to: delete a dataset or to delete/edit a map. For editing a map I mean to change the title and description.

I wouldn't include these options in Kepler. I would make users go to the CARTO dashboard to manage their maps. This is a quick wireframe.

![Group 8](https://user-images.githubusercontent.com/46195278/66550263-50a87980-eb45-11e9-9d8b-b001c45fffa4.png)


For two reasons:
- Increase the use of CARTO so users can discover its value.
- Don't duplicate the management of maps/datasets.

__________

>  with both tabs opened, but only with a reduced number of maps to make room for seeing the content of both.

The modal has a limited height (600 px) in Kepler styles, so it's not possible to display more than one dataset.

Anyway, I worked on making more room for the datasets section, so the user can deduce there's a scroll.

In this way, they can see the rest of their maps/datasets by clicking on the "Load more" option.

![Group 9](https://user-images.githubusercontent.com/46195278/66550747-55b9f880-eb46-11e9-9e9b-a72f12e13052.png)

**Comment by MireyaD** [comment]
I also created a v3 for the storage engine with the entry point near the share button. I think it may be a good option, it's not as intrusive as v2, and it's easier to find as it's always displayed.

![Storage v3 hover](https://user-images.githubusercontent.com/46195278/66552884-6c624e80-eb4a-11e9-8307-66cfce88c522.png)

**Invision link to Storage Engine v3: https://invis.io/TPTSVDX2KF5#/387874828_Storage_V3**

 What do you think?

**Comment by VictorVelarde** [comment]
## Tech notes
@alasarr I have updated the **3. Technical Notes** block with your comments ([up here](https://github.com/CartoDB/kepler.gl/issues/13#issuecomment-533514417)), making a better description of the *generic approach* (section 3.1.). I extracted all CARTO-related specific notes to a different section (3.2.) so we can decide later on how to proceed. Please @rjimenezda have a look at those notes (I used toolkit code as a reference).

## Design & Dashboard interactions
I'm also more keen on relying in the Dashboard for data management tasks as @MireyaD proposes, but we probably still need more internal discussion to close the definition.

For example, regarding to 'Datasets' list in Kepler, we have 2 options we have not talked about explicitly:

- a) display just *kepler* custom-datasets: that means, datasets that have been uploaded to CARTO through this integration or
- b) display both kepler datasets & regular ones.

IMO displaying both is nicer, and probably that's what's expected, as it allows the client to use a broader set of datasets, but it implies some more analysis in the kepler side we haven't done yet.  

As a  related note, 'custom-datasets' will have 2 copies in our platform (an internal, raw & read-only copy + a cartodbfied copy that would appear in the Dashboard just as any other 'Dataset' and it could be edited). That has several implications regarding to CRUD operations from Kepler.

**Comment by ana-md** [comment]
> I'm also more keen on relying in the Dashboard for data management tasks as @MireyaD proposes, but we probably still need more internal discussion to close the definition.

Completely agree @VictorVelarde that we need more internal discussion about this (@MireyaD and I were talking about that yesterday and we had the same questions/doubts).

**Comment by ana-md** [comment]
Closing this issue as we have divided it into two different steps after rescheduling the project. The new issue can be found [here](https://github.com/CartoDB/kepler.gl/issues/29).
