### ISSUE TITLE
Ensure required APIs & OAuth support

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#16]
There are several **APIs** that can be used as-is, as for example the `sql-api`, but some new ones might be required: eg. a generic api for storing (maybe `custom-store`?) or one to change dataset's privacy

Also,  to ensure a smooth & optimal use, all the APIs need to support **OAuth**, so for example new **scopes** might be required (read-all datasets for sql-api?)

The objective of this issue is to list the status all the required APIs and its support regarding to OAUTH

**Comment by VictorVelarde** [comment]
Please @rjimenezda gather the current info that we have, after your talks with @alrocar

**Comment by rjimenezda** [comment]
We'll need 

- `schemas:c`: to create new tables, the ones for custom store etc
- `datasets:metadata`: to list the datasets from the user's account.

What I've talked with @alrocar so far:

- Validate the approach, for the `custom-store` system. This won't be an API in the mid term, but an external library that does everything on the client.
- We'll need the 'read any dataset' scope if we want to import arbitrary data from CARTO with OAuth and not introduce an awful UX flow. I proposed this being `dataset:rw:*`, where the star might be a special case or even a proper regexp.
- We also need a way to change dataset privacy for the `custom-store`. There's going to be a CORS-enabled API endpoint for this, but in the meantime we can try a SQL hack*.

We were going to do the privacy first and the ready any dataset later, but since we have a hack for one, but not for the other, maybe we should change the priority?

Thoughts @alrocar? Sorry for `marearte`

* The SQL hack is only acceptable because we're doing it on non-'cartodbfied' tables (custom-store metadata table and kepler data). Because of how ghost tables work, cartodbfied tables should change their privacy via a proper api.

**Comment by alrocar** [comment]
From the OAuth side we have:

- new scope `datasets:r:*` it will allow to read all datasets in the user account. Eventually the `*` could by a regex, but at the moment it's simpler to just support `*`
- new API + scope to edit datasets metadata. Let's try to validate first the `SQL hack`.

I've been taking a look at the code and:

- For the org. owner or a regular user you can do a `GRANT SELECT ON table TO publicuser`
- But for the rest of org users we use this role `cartodb_publicuser_{id}`

In each case you can now the role of the `default_public` key, by doing this request to the SQL API:

`https://aromeu.carto.com/api/v2/sql?q=select+current_user&api_key=default_public`

Then you can do the `GRANT` to the role returned.

**Comment by rjimenezda** [comment]
Great, I'll fetch that as well as the basic user info

**Comment by VictorVelarde** [comment]
I think there's nothing more here to be defined right now.
Feel free to reopen this @rjimenezda if something NEW is required from APIs / OAuth
