### ISSUE TITLE
[Public map] Run basic tests v0.1

### ISSUE THREAD

**Issue by ana-md** [CartoDB/kepler.gl#24]
**Goal:** 
Run the tests defined previously [in this issue](https://github.com/CartoDB/kepler.gl/issues/20) when the internal release for v0.1 (Share map via URL) is ready. 

[These](https://docs.google.com/spreadsheets/d/16TVG1qrLfQ0sDdZMbOEnA3oHlQYd4HSWPkqTxlV8K-s/edit#gid=1364534589) are the different tests depending on users and browsers.

**Comment by ana-md** [comment]
As the pricing strategy definition is still in-progress, we proposed to do the tests for this phase with two different type of users in staging (https://carto-staging.com), doing as follows: 
1. Individual trial user --> Just by doing `Sign up` and creating a new user. 
2. Individual paid user --> Doing the `Upgrade process` with the trial user by using this testing card number from Recurly: https://docs.recurly.com/docs/test#section-test-credit-card-numbers
3. Users from an Organization

**Comment by VictorVelarde** [comment]
I think we should add a test with users from an org, to properly check OAuth in those conditions.

**Comment by ana-md** [comment]
> I think we should add a test with users from an org, to properly check OAuth in those conditions.

Ok! I have edited the [comment above](https://github.com/CartoDB/kepler.gl/issues/24#issuecomment-552357333) including this type of users.

**Comment by ana-md** [comment]
Tests have been done, documented in the [spreadsheet](https://docs.google.com/spreadsheets/d/16TVG1qrLfQ0sDdZMbOEnA3oHlQYd4HSWPkqTxlV8K-s/edit#gid=1364534589) and [discussed](https://github.com/orgs/CartoDB/projects/94#card-29212157) with the team in the daily!

**Comment by VictorVelarde** [comment]
Bringing here the Notes from the tests, to remove the card:

**bugs**:
- ~A possible problem rendering taxi datasets vis~. It looks like a rendering temporary glitch

**ux improvements**:
- Clean shared url when closing window
- Upload copy? have some specific copy for Carto, instead of the generic current one 
- Missing icons in staging for Github / Google when using OAuth2
- (edited) --> https://github.com/CartoDB/kepler.gl/issues/36 for this block

**feature discussion**:
- Overwrite last viz? (vs Save as) --> to discuss

**performance**:
- Performance in big datasets is low (kepler.gl). But it doesn't look like upload / load to CARTO makes a difference there

**Comment by VictorVelarde** [comment]
For the process (to be repeated in the future) we have used this checklist: https://github.com/CartoDB/kepler.gl/issues/35
